site_name: Traverser
site_description: Evidence-based path traversal scanner
repo_url: https://github.com/ethercod3/traverser
repo_name: ethercod3/traverser

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - scheme: default
      primary: lime
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Swith to light mode
nav:
  - Overview: index.md
  - Usage: usage.md
  - Development: development.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
